import type { RottenBuildSummary } from "./build";
import type { RottenSkillId, RottenWeaponId, RottenWeaponStyle } from "./loadout";
import type { RottenRouteId, RottenStageNumber } from "./routes";
import type { RottenUpgradeId } from "./upgrades";

export type RottenRunPhase = "loadout" | "route-choice" | "encounter" | "reward-choice" | "dead";

export interface RottenRunDebugSnapshot {
  readonly scene: "RottenRunScene";
  readonly phase: RottenRunPhase;
  readonly schemaVersion: number;
  readonly seed: string;
  readonly planId: string;
  readonly stage: RottenStageNumber;
  readonly routeOptions: readonly [RottenRouteId, RottenRouteId];
  readonly selectedRoute: RottenRouteId | null;
  readonly weapon: RottenWeaponId | null;
  readonly skill: RottenSkillId | null;
  readonly upgrades: readonly RottenUpgradeId[];
  readonly buildSummary: RottenBuildSummary;
  readonly graft: number;
  readonly hp: { readonly current: number; readonly max: number } | null;
  readonly livingEnemies: number;
  readonly eliteCount: 0;
  readonly bossHealth: null;
  readonly bossPhase: null;
  readonly elapsedActiveMilliseconds: number;
  readonly result: null;
  readonly traceDigest: string;
  readonly wave: 0 | 1 | 2;
  readonly wavesCleared: number;
  readonly spawnHistory: readonly string[];
  readonly enemyStates: readonly string[];
  readonly enemyGeometry: readonly string[];
  readonly enemyReacquisition: readonly string[];
  readonly enemyTell: string;
  readonly attackCount: number;
  readonly attackHitCount: number;
  readonly weaponStyle: RottenWeaponStyle | "";
  readonly weaponCooldownMs: number;
  readonly weaponHeat: number;
  readonly weaponRecovering: boolean;
  readonly skillUseCount: number;
  readonly skillHitCount: number;
  readonly skillReady: boolean;
  readonly offerIds: readonly RottenUpgradeId[];
  readonly offerPrices: readonly number[];
  readonly healAvailable: boolean;
  readonly marketStatus: "" | "open" | "resolved";
  readonly marketStage: 1 | null;
  readonly marketRoute: RottenRouteId | null;
  readonly marketChoice: string;
  readonly marketTraceEvent: string;
  readonly routeHistory: readonly string[];
  readonly rewardFeedback: string;
  readonly rewardFeedbackReason: string;
  readonly rewardDecisionCount: 0 | 1;
  readonly combatObjectCount: number;
}
