import type { RottenBuildSummary } from "./build";
import type { RottenSkillId, RottenWeaponId, RottenWeaponStyle } from "./loadout";
import type { RottenRouteId, RottenStageNumber } from "./routes";
import type { RottenUpgradeId } from "./upgrades";

export type RottenRunPhase = "loadout" | "route-choice" | "encounter" | "reward-choice" | "dead";

export interface RottenRunDebugSnapshot {
  readonly scene: "RottenRunScene";
  readonly phase: RottenRunPhase;
  readonly schemaVersion: number;
  readonly seed: string;
  readonly planId: string;
  readonly stage: RottenStageNumber;
  readonly routeOptions: readonly [RottenRouteId, RottenRouteId];
  readonly selectedRoute: RottenRouteId | null;
  readonly weapon: RottenWeaponId | null;
  readonly skill: RottenSkillId | null;
  readonly upgrades: readonly RottenUpgradeId[];
  readonly buildSummary: RottenBuildSummary;
  readonly graft: number;
  readonly hp: { readonly current: number; readonly max: number } | null;
  readonly livingEnemies: number;
  readonly eliteCount: number;
  readonly currentEliteCount: number;
  readonly eliteDefeatedCount: number;
  readonly eliteDefeatedVariants: readonly string[];
  readonly eliteBountyGraft: number;
  readonly eliteArmorBreakCount: number;
  readonly eliteEnrageCount: number;
  readonly bossHealth: null;
  readonly bossPhase: null;
  readonly elapsedActiveMilliseconds: number;
  readonly result: null;
  readonly traceDigest: string;
  readonly wave: 0 | 1 | 2;
  readonly stageWavesCleared: number;
  readonly wavesCleared: number;
  readonly spawnHistory: readonly string[];
  readonly enemyStates: readonly string[];
  readonly enemyGeometry: readonly string[];
  readonly enemyReacquisition: readonly string[];
  readonly enemyTell: string;
  readonly attackCount: number;
  readonly attackHitCount: number;
  readonly weaponStyle: RottenWeaponStyle | "";
  readonly weaponCooldownMs: number;
  readonly weaponHeat: number;
  readonly weaponRecovering: boolean;
  readonly skillUseCount: number;
  readonly skillHitCount: number;
  readonly skillCooldownMs: number;
  readonly skillReady: boolean;
  readonly grudgeRemainingMs: number;
  readonly maxGrudgeBonusDamage: number;
  readonly compoundBonusDamage: number;
  readonly maxCompoundBonusDamage: number;
  readonly maxTotalWeaponBonusDamage: number;
  readonly compoundExpiresInMs: number;
  readonly dashCooldownMs: number;
  readonly dashWakeCount: number;
  readonly dashWakeHitCount: number;
  readonly deadLetterCount: number;
  readonly deadLetterHitCount: number;
  readonly waveHealCount: number;
  readonly waveHealRestored: number;
  readonly shieldBlockCount: number;
  readonly shieldFlankHitCount: number;
  readonly shieldOpenCount: number;
  readonly shieldOpenSources: readonly string[];
  readonly hazardTelegraphCount: number;
  readonly hazardActiveCount: number;
  readonly hazardActivationCount: number;
  readonly hazardHitCount: number;
  readonly hazardClearCount: number;
  readonly hazardExpiryCount: number;
  readonly hazardTeardownCount: number;
  readonly offerIds: readonly RottenUpgradeId[];
  readonly offerPrices: readonly number[];
  readonly healAvailable: boolean;
  readonly marketStatus: "" | "open" | "resolved";
  readonly marketStage: 1 | 2 | null;
  readonly marketRoute: RottenRouteId | null;
  readonly marketChoice: string;
  readonly marketTraceEvent: string;
  readonly routeHistory: readonly string[];
  readonly rewardFeedback: string;
  readonly rewardFeedbackReason: string;
  readonly rewardDecisionCount: 0 | 1 | 2;
  readonly combatObjectCount: number;
  readonly canvasCount: number;
}
